// GENERATED by apps/cloud/sync-engine.mjs from packages/snoutpod/src/control/functions.ts
// Do not edit here. Edit the original, then re-run the script (deploy.sh does, and so
// do the dashboard's and the CLI's own builds).
/**
 * Snout Functions: what a deployment IS, and what may be done with one.
 *
 * `docs/cloud/STACK.md` Phase H. Everything in this file is a value in and a decision
 * out — the same contract every other module under `control/` keeps, and the reason it
 * can be synced into a Snout Function by `apps/cloud/sync-shared.sh` and used unchanged
 * by the CLI, the control plane and the host agent. There is one bundle format, one
 * digest, one name rule and one set of limits, and all four live here rather than in the
 * three places that would otherwise each have a copy.
 *
 * ## The bundle, and why it is a JSON document rather than a tarball
 *
 * A function is source code. It is a handful of small text files, it is read by a Deno
 * runtime that wants a directory, and it has to survive a journey through a JSON API and
 * a `bytea` column. A tar or a zip would mean writing a container format and a parser in
 * three languages (Node for the CLI, Deno for the control plane and the runtime,
 * TypeScript for the host) with a corrupted deployment as the failure mode. A JSON
 * document with the files in it is a format all three already have, and gzip is
 * `node:zlib` and `DecompressionStream`, both of which are in the platform.
 *
 * **Text only, and that is a v1 limitation rather than an oversight.** A file that is not
 * valid UTF-8 is refused with a sentence, so a customer who tries to ship a `.wasm` is
 * told it is not supported instead of finding out from a runtime error. Binary assets
 * belong in Storage (Phase F), which exists and is the right home for them.
 *
 * ## The digest is the identity, and that is what makes the cache safe
 *
 * A bundle is named by the SHA-256 of its CANONICAL bytes — the same files in the same
 * order with the same separators, whatever order the caller happened to put them in. So:
 *
 *   * a redeploy of unchanged source is the same digest and costs nothing;
 *   * a redeploy of changed source is a DIFFERENT object, at a different key, so no cache
 *     anywhere can serve stale code and nothing has to be invalidated;
 *   * a host that has the digest already does not fetch it again, and a host that has
 *     never seen it fetches from object storage, which is the source of truth
 *     (STACK.md's sentence 1).
 *
 * That last point is why the cache is keyed by digest and not by `<ref>/<name>`: a cache
 * keyed by name has to be told when it is wrong, and being told is the part that fails.
 *
 * ## What is deliberately NOT here
 *
 * Anything that reaches a network or a disk. The courier that moves a bundle into object
 * storage is `host/functionRuntime.ts` (which builds arguments) and the host agent (which
 * runs them); the wrapping of a secret is `_shared/secrets.ts` in the control plane, which
 * holds the key this module must never see.
 */

/**
 * The bundle format's version, on the wire and in the digest.
 *
 * In the document rather than only in the key, so a bundle read back out of object
 * storage says what it is without the key having to be parsed.
 */
export const BUNDLE_FORMAT = 1;

/**
 * What a function may be called.
 *
 * It becomes a URL path segment (`/functions/v1/<name>`), a directory name in the
 * runtime's cache and a row's primary key, so the rule is checked once, here, and every
 * consumer trusts it afterwards. No dot and no slash is the security half: a name that
 * cannot contain `..` or `/` is a name no path built from it can escape with.
 *
 * Deliberately a superset of the kebab-case Upstream examples use and a subset of what a
 * filesystem would take, so a function called `send-email` and one called `sendEmail`
 * both work and neither can be `../../etc`.
 */
const FUNCTION_NAME = /^[A-Za-z0-9][A-Za-z0-9_-]{0,47}$/;

export function isFunctionName(value: string): boolean {
	return FUNCTION_NAME.test(value);
}

export function assertFunctionName(value: string): string {
	if (!isFunctionName(value)) {
		throw new Error(
			`not a function name: ${JSON.stringify(value)}. Letters, digits, hyphens and underscores, up to 48 characters, starting with a letter or a digit.`
		);
	}
	return value;
}

/**
 * Which function a request is for, from the path the front door forwards.
 *
 * The door strips `/functions/v1`, so what arrives is `/<name>` or `/<name>/anything`,
 * and everything after the name is the function's own business — a function is a server
 * and may route inside itself, which is what `serve` in somebody's `index.ts` does with
 * a router.
 *
 * Here rather than in the proxy or the runtime because BOTH need it and they are
 * different languages running on different machines: the door uses it to decide whether
 * this particular function is one that may be called without a key, and the runtime uses
 * it to decide which bundle to start. Two copies of "where does the name end" is how one
 * of them ends up allowing `/hello/../admin`.
 *
 * Null for anything that is not a function call, INCLUDING a name that breaks the rule.
 * A caller that gets null answers 404 rather than reaching for a default.
 */
export function functionNameFromPath(path: string): string | null {
	const clean = (path.split('?')[0] ?? '').replace(/^\/+/, '');
	const first = clean.split('/')[0] ?? '';
	return isFunctionName(first) ? first : null;
}

/**
 * A path inside a bundle.
 *
 * Relative, forward slashes, no `.` or `..` segment, no leading slash, no backslash. The
 * runtime writes these under a directory it owns, so this predicate is the whole of what
 * stops a bundle writing outside it. It is checked when a bundle is BUILT and again when
 * one is READ, because the two happen on different machines and only one of them is ours.
 */
// A leading underscore is allowed because `_shared/` is Upstream's own convention for code
// every function imports (`upstream/functions/_shared`), and the control plane's functions use
// it. A leading dot is still refused: that is `.env`.
const PATH_SEGMENT = /^[A-Za-z0-9_][A-Za-z0-9._-]*$/;

export function isBundlePath(value: string): boolean {
	if (value.length === 0 || value.length > 255) {
		return false;
	}
	if (value.includes('\\') || value.startsWith('/')) {
		return false;
	}
	const parts = value.split('/');
	if (parts.length > 8) {
		return false;
	}
	return parts.every((part) => part !== '.' && part !== '..' && PATH_SEGMENT.test(part));
}

/** One file of a function's source. */
export interface BundleFile {
	readonly path: string;
	readonly text: string;
}

/** A deployable function, before it has been serialised. */
export interface FunctionBundle {
	readonly snoutfn: number;
	/** Which file the runtime starts. Always one of `files`. */
	readonly entrypoint: string;
	readonly files: readonly BundleFile[];
}

/**
 * How big a bundle may be, uncompressed, whatever the tier.
 *
 * Two megabytes of TEXT is an enormous function — the whole of this repository's Snout
 * Function directory is a fraction of it — and the cap is not really about the file. It
 * is about the courier: a bundle travels through a JSON request body and a `bytea`
 * column on its way to object storage, so a number that is generous for source code and
 * small for a network is the number that keeps that path boring.
 *
 * It is not per tier on purpose. A bigger allowance is not a feature anybody wants and a
 * per-tier limit here would be a refusal a paying customer hits for no reason they can
 * act on. Where the tiers differ is what an invocation may CONSUME, which is below.
 */
export const MAX_BUNDLE_BYTES = 2 * 1024 * 1024;

/** And how many files, so a pathological bundle is refused before it is walked. */
export const MAX_BUNDLE_FILES = 200;

/**
 * Build a bundle from files a caller has read off a disk.
 *
 * Refuses rather than repairs, and the sentences are the ones a person sees in the CLI,
 * so they say what to do and not only what is wrong.
 */
export function buildBundle(options: {
	entrypoint: string;
	files: readonly BundleFile[];
}): FunctionBundle {
	const { entrypoint } = options;
	if (options.files.length === 0) {
		throw new Error('there is nothing in this function to deploy');
	}
	if (options.files.length > MAX_BUNDLE_FILES) {
		throw new Error(
			`a function may hold ${MAX_BUNDLE_FILES} files and this one has ${options.files.length}`
		);
	}
	const seen = new Set<string>();
	for (const file of options.files) {
		if (!isBundlePath(file.path)) {
			throw new Error(`${JSON.stringify(file.path)} is not a path a function may contain`);
		}
		if (seen.has(file.path)) {
			throw new Error(`${file.path} appears twice`);
		}
		seen.add(file.path);
	}
	if (!seen.has(entrypoint)) {
		throw new Error(`the entrypoint ${JSON.stringify(entrypoint)} is not one of the files`);
	}
	// Sorted HERE rather than at serialisation, so the object a caller inspects is the
	// object that gets hashed and there is no second ordering anywhere.
	const files = [...options.files].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
	const bundle: FunctionBundle = { snoutfn: BUNDLE_FORMAT, entrypoint, files };
	const bytes = bundleBytes(bundle);
	if (bytes.length > MAX_BUNDLE_BYTES) {
		throw new Error(
			`this function is ${Math.round(bytes.length / 1024)} KB and the limit is ${MAX_BUNDLE_BYTES / 1024} KB. A function is source code; put large files in Storage.`
		);
	}
	return bundle;
}

/**
 * The bundle's canonical bytes: the one serialisation the digest is taken over.
 *
 * `JSON.stringify` with the keys written in a fixed order by construction rather than by
 * hoping the engine preserves insertion order — it does, but a digest that depends on an
 * engine's object semantics is a digest that changes when somebody refactors. Every
 * consumer that needs the bytes calls this; nothing re-serialises.
 */
export function bundleBytes(bundle: FunctionBundle): Uint8Array {
	const files = bundle.files
		.map((file) => `{"path":${JSON.stringify(file.path)},"text":${JSON.stringify(file.text)}}`)
		.join(',');
	const text = `{"snoutfn":${bundle.snoutfn},"entrypoint":${JSON.stringify(bundle.entrypoint)},"files":[${files}]}`;
	return new TextEncoder().encode(text);
}

/**
 * Read bytes back into a bundle, checking every rule again.
 *
 * The runtime and the host both call this on bytes that came off a network, and neither
 * of them may assume the writer was us: a bundle is customer content, and the path check
 * is what stops one writing outside the directory it is unpacked into. So the checks are
 * repeated rather than trusted, which is the same reason `cloud_projects.ref` is checked
 * at the boundary as well as generated.
 */
export function readBundle(bytes: Uint8Array): FunctionBundle {
	if (bytes.length > MAX_BUNDLE_BYTES) {
		throw new Error('this bundle is larger than a bundle may be');
	}
	let parsed: unknown;
	try {
		parsed = JSON.parse(new TextDecoder('utf-8', { fatal: true }).decode(bytes));
	} catch {
		throw new Error('this bundle is not the document a bundle is');
	}
	const document = parsed as Partial<FunctionBundle>;
	if (document === null || typeof document !== 'object' || document.snoutfn !== BUNDLE_FORMAT) {
		throw new Error(`this bundle is not format ${BUNDLE_FORMAT}`);
	}
	if (typeof document.entrypoint !== 'string' || !Array.isArray(document.files)) {
		throw new Error('this bundle has no entrypoint or no files');
	}
	const files: BundleFile[] = [];
	for (const raw of document.files) {
		const file = raw as Partial<BundleFile>;
		if (typeof file?.path !== 'string' || typeof file?.text !== 'string') {
			throw new Error('a file in this bundle is not a path and a text');
		}
		files.push({ path: file.path, text: file.text });
	}
	return buildBundle({ entrypoint: document.entrypoint, files });
}

/**
 * Where a bundle lives, forever, under the project's own prefix.
 *
 * `<ref>/functions/<digest>.snoutfn` — a third-party-readable name that says nothing
 * about which function it is, on purpose: a digest is content, and two projects that
 * deploy the same code get two objects rather than sharing one, because a shared object
 * is a deletion one project can perform on another.
 *
 * The prefix helper is `refs.ts`'s `functionPrefix`, which is where the reclaimer's
 * licence (`<ref>/`) is stated. This composes on top of it rather than building a key of
 * its own.
 */
export function bundleObjectName(digest: string): string {
	assertDigest(digest);
	return `${digest}.snoutfn`;
}

const DIGEST = /^[0-9a-f]{64}$/;

export function assertDigest(value: string): string {
	if (!DIGEST.test(value)) {
		throw new Error(`not a bundle digest: ${JSON.stringify(value)}`);
	}
	return value;
}

/**
 * What one invocation may consume, per tier.
 *
 * These are the numbers `EdgeRuntime.userWorkers.create` takes, named the way it names
 * them, so the main worker passes them through rather than translating. They come out of
 * `cloud_limits` and reach the runtime on the project's manifest.
 *
 * **The wall clock has a ceiling that is not ours**: the front door's `upstreamTimeoutMs`
 * is 60 seconds, so a function allowed to run for longer would be killed by the proxy
 * with a 502 rather than by the runtime with a sentence. `capInvocationLimits` is where
 * that is enforced, and it exists so the two numbers cannot drift apart silently.
 */
export interface InvocationLimits {
	readonly memoryMb: number;
	readonly wallMs: number;
	/** The CPU budget. Exceeding it is the runtime's business, not the clock's. */
	readonly cpuMs: number;
}

/** The proxy's upstream timeout, which is the hard ceiling on a wall clock. */
export const PROXY_UPSTREAM_TIMEOUT_MS = 60_000;

/**
 * The floor under everything, used when a control plane older than this sends nothing.
 *
 * Same rule as `tuningEnv`: a missing number is a working function on a conservative
 * default and never a function that will not start.
 */
export const DEFAULT_INVOCATION_LIMITS: InvocationLimits = {
	memoryMb: 128,
	wallMs: 10_000,
	cpuMs: 2_000
};

export function capInvocationLimits(limits: Partial<InvocationLimits> | null | undefined): InvocationLimits {
	const memoryMb = clamp(limits?.memoryMb, DEFAULT_INVOCATION_LIMITS.memoryMb, 16, 1024);
	const cpuMs = clamp(limits?.cpuMs, DEFAULT_INVOCATION_LIMITS.cpuMs, 50, 300_000);
	const wallMs = clamp(
		limits?.wallMs,
		DEFAULT_INVOCATION_LIMITS.wallMs,
		100,
		// A second less than the proxy gives up, so the refusal a customer sees is the
		// runtime's ("your function ran too long") and not the door's ("bad gateway").
		// Which of the two they get decides whether they can fix it.
		PROXY_UPSTREAM_TIMEOUT_MS - 1_000
	);
	return { memoryMb, wallMs, cpuMs };
}

function clamp(value: number | null | undefined, fallback: number, low: number, high: number): number {
	if (typeof value !== 'number' || !Number.isFinite(value)) {
		return fallback;
	}
	return Math.min(high, Math.max(low, Math.round(value)));
}

/**
 * The hard CPU limit, derived rather than configured.
 *
 * functions-runtime takes two: a SOFT limit, at which it asks the isolate to stop and lets it
 * write a response, and a HARD one, at which the isolate is destroyed. Making the hard
 * one a separate configuration value would mean two numbers a person has to keep in a
 * relationship they cannot see; making it a multiple means the soft limit is the only
 * number anybody sets and the isolate always gets a chance to say what happened.
 */
export function hardCpuMs(limits: InvocationLimits): number {
	return Math.min(limits.wallMs, Math.round(limits.cpuMs * 1.5) + 500);
}

/**
 * What the runtime is told about one project.
 *
 * Written by the host agent into its cache and read by the main worker. It carries
 * SECRETS — the customer's own function environment, unwrapped — which is why it is a
 * file in a directory the runtime container mounts read-only rather than anything that
 * travels over a network the runtime can reach. See the egress note in
 * `host/functionRuntime.ts`.
 */
export interface ProjectFunctionManifest {
	readonly ref: string;
	/**
	 * What everything below hashes to, so a cache can be compared cheaply.
	 *
	 * A fingerprint rather than a counter, which is the shape `cloud_realtime_fingerprint`
	 * and `cloud_storage_tenant` already use: a counter needs something to remember to
	 * bump it on every path that changes anything, and a path that forgets is a host
	 * serving stale code with nothing anywhere to notice. Computed in SQL from the rows
	 * (migration 041), so it has no writer to forget.
	 */
	readonly fingerprint: string;
	readonly functions: readonly DeployedFunction[];
	readonly limits: InvocationLimits;
	/**
	 * The customer's own secrets, already unwrapped, plus the few we set for them.
	 * Every function in the project gets all of them, which is what Upstream does and
	 * what a customer moving from it expects.
	 *
	 * Composed in the CONTROL PLANE, including the `UPSTREAM_*` variables, and written
	 * out by the host verbatim. The host could derive the URL and mint the keys — it has
	 * neither the key-minting code nor a reason to learn what a Upstream variable is, and
	 * a second place that mints an `anon` key is two `anon` keys for one project.
	 */
	readonly env: Readonly<Record<string, string>>;
}

export interface DeployedFunction {
	readonly name: string;
	readonly digest: string;
	readonly entrypoint: string;
	/**
	 * Whether the runtime refuses a call with no valid project JWT before the function
	 * is started.
	 *
	 * Upstream's default is on, and so is ours: a function is arbitrary code with a
	 * network attached, and the failure of getting the default wrong is a stranger
	 * running it. A webhook receiver turns it off deliberately, which is a choice made
	 * at deploy time and recorded on the audit log.
	 */
	readonly verifyJwt: boolean;
}

/**
 * A secret's NAME, which is the half of a secret that is not a secret.
 *
 * Environment variables, so the C rule, plus a refusal of the names the runtime sets
 * itself. Letting a customer set `UPSTREAM_SERVICE_ROLE_KEY` would not be a
 * vulnerability — it is their own project's key — but letting them set the ones that say
 * WHICH project this is would be, so the reserved list is checked and not assumed.
 */
const SECRET_NAME = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/;

/**
 * Names a customer may not take, because the runtime writes them and something downstream
 * believes them.
 *
 * `SNOUT_*` is ours by prefix. The three Upstream ones are set from the project's own
 * keys, so overwriting them would only break the customer's own function — they are
 * refused anyway, because a value that is silently ignored is worse than a refusal, and
 * because a function that reads `UPSTREAM_URL` and gets a lie is a debugging session
 * nobody wins.
 */
export const RESERVED_SECRET_NAMES: readonly string[] = [
	'UPSTREAM_URL',
	'UPSTREAM_ANON_KEY',
	'UPSTREAM_SERVICE_ROLE_KEY',
	'UPSTREAM_DB_URL'
];

export function checkSecretName(name: string): string | null {
	if (!SECRET_NAME.test(name)) {
		return `${JSON.stringify(name)} is not an environment variable name: letters, digits and underscores, not starting with a digit.`;
	}
	if (name.startsWith('SNOUT_')) {
		return `names beginning with SNOUT_ are set by the platform, so ${name} cannot be one of yours.`;
	}
	if (RESERVED_SECRET_NAMES.includes(name)) {
		return `${name} is set for you from this project's own keys and cannot be overridden.`;
	}
	return null;
}

/** How much a project's secrets may weigh in total. An environment is not a database. */
export const MAX_SECRET_BYTES = 64 * 1024;

/**
 * May this project deploy another function?
 *
 * A refusal with a sentence rather than a boolean, for the reason every other quota here
 * gives one: the caller prints it, and a caller that has to compose the sentence is a
 * caller that will compose a different one from the next surface.
 *
 * **Snout Functions are free (TBD-3), so there is no plan gate here at all** — what bounds
 * a free project is this count and the per-invocation limits, not a missing feature. A
 * `SNOUT_PLAN_REQUIRED` in this file would be a bug.
 */
export interface FunctionAllowance {
	readonly deployed: number;
	readonly maxFunctions: number | null;
}

export function mayDeployFunction(
	allowance: FunctionAllowance,
	name: string,
	existing: readonly string[]
): { ok: true } | { ok: false; reason: string } {
	if (!isFunctionName(name)) {
		return { ok: false, reason: `${JSON.stringify(name)} is not a name a function may have` };
	}
	if (existing.includes(name)) {
		// Replacing one is not spending a slot, and treating it as if it were is how a
		// project at its limit becomes a project that cannot fix its own bug.
		return { ok: true };
	}
	const max = allowance.maxFunctions;
	if (max !== null && allowance.deployed >= max) {
		return {
			ok: false,
			reason: `this plan runs ${max} functions and this project already has ${allowance.deployed}. Delete one, or move to a larger plan.`
		};
	}
	return { ok: true };
}

/**
 * What a host still has to do about a project's functions.
 *
 * The host compares what the control plane says a project has against what is in its own
 * cache, and this says what is left. Pure, so the host agent's tick is a call and a loop
 * rather than a nest of conditions nobody tests.
 *
 * The two jobs are deliberately separate, because they fail differently and only one of
 * them is on the critical path of an invocation:
 *
 *   * **fetch** — a digest this host has not got. Until it is fetched the function cannot
 *     run here at all, so this is urgent and is what a cold host does first.
 *   * **archive** — a bundle that is still only in the control plane's staging table and
 *     not yet in object storage. Until it is shipped, sentence 1 is not true of it. It is
 *     not urgent for an invocation and it must never block one.
 */
export interface FunctionWork {
	readonly fetch: readonly string[];
	readonly archive: readonly string[];
	readonly evict: readonly string[];
}

export function planFunctionWork(options: {
	/** Digests the project's live functions refer to. */
	readonly wanted: readonly { digest: string; archived: boolean }[];
	/** Digests this host already has unpacked. */
	readonly cached: readonly string[];
}): FunctionWork {
	const cached = new Set(options.cached);
	const wanted = new Set(options.wanted.map((one) => one.digest));
	const fetch: string[] = [];
	const archive: string[] = [];
	for (const one of options.wanted) {
		if (!cached.has(one.digest) && !fetch.includes(one.digest)) {
			fetch.push(one.digest);
		}
		if (!one.archived && !archive.includes(one.digest)) {
			archive.push(one.digest);
		}
	}
	// A digest nothing refers to any more. Evicting it is housekeeping and never
	// correctness: object storage still has it, so a cache that is wrong is a cache that
	// is slow, which is the property the whole design is built on.
	const evict = options.cached.filter((digest) => !wanted.has(digest));
	return { fetch, archive, evict };
}
